# Generated by Django 3.0.3 on 2020-02-15 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('barang_id', models.AutoField(primary_key=True, serialize=False)),
                ('barang_nama', models.CharField(max_length=255)),
                ('barang_brand', models.CharField(max_length=255)),
                ('barang_jenis', models.CharField(max_length=255)),
                ('barang_spek', models.CharField(max_length=500)),
                ('barang_created', models.DateTimeField(auto_now_add=True)),
                ('barang_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventaris',
            fields=[
                ('inv_id', models.AutoField(primary_key=True, serialize=False)),
                ('inv_pengadaan_petugas', models.CharField(max_length=255)),
                ('inv_pengadaan_tgl', models.DateTimeField(auto_now_add=True)),
                ('inv_pengadaan_harga', models.FloatField()),
                ('inv_perbaikan_petugas', models.CharField(max_length=255)),
                ('inv_perbaikan_tgl', models.DateTimeField(auto_now_add=True)),
                ('inv_lokasi', models.CharField(max_length=255)),
                ('inv_status', models.CharField(choices=[('aktif', 'Aktif'), ('rusak', 'Rusak'), ('hilang', 'Hilang'), ('dilelang', 'Dilelang')], default='aktif', max_length=10)),
                ('inv_barang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventori.Barang')),
            ],
        ),
    ]
