# Generated by Django 3.0.3 on 2020-02-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventori', '0002_auto_20200215_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='barang_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventaris',
            name='inv_pengadaan_tgl',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventaris',
            name='inv_perbaikan_tgl',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
