# Generated by Django 3.0.3 on 2020-02-16 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventori', '0004_inventaris_inv_nomor'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='barang_image',
            field=models.ImageField(default=datetime.datetime(2020, 2, 16, 7, 43, 42, 993121, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
