# Generated by Django 3.0.3 on 2020-02-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventori', '0005_barang_barang_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='barang_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
