# Generated by Django 3.0.3 on 2020-02-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventori', '0006_auto_20200216_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='barang_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
