# Generated by Django 3.0.3 on 2020-02-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventori', '0007_auto_20200216_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='barang_image',
            field=models.FileField(default='default.png', upload_to=''),
        ),
    ]
